### ISSUE TITLE
Welcome Screens

### ISSUE THREAD

**Issue by eug48** [HealthHackAu2020/Oscar#1]
These are what's shown to the user immediately after they install the app.
Many apps have several screens in a swipe-slider style layout

**Comment by m0un10** [comment]
I think more information is need on this. I've created a placeholder [here](https://github.com/HealthHackAu2020/Oscar/blob/dev/features/onboarding.feature#L18-L19)

**Comment by m0un10** [comment]
closing due to end of healthhack. feel free to re-open later
