### ISSUE TITLE
Backend-Frontend integration

### ISSUE THREAD

**Issue by eug48** [HealthHackAu2020/Oscar#12]
I've started using Redux for frontend data management, so basically the entire app state (mood history, activity history, favourite activities) can be serialised into a single JSON object.

So it currently seems to me that a fairly easy & effective option could be to simply save the whole state to the backend as a JSON object after every change, and load the state after a new log-in. There could be some logic to warn about potentially unintended overwriting.

@m0un10 @NickSolante

**Comment by m0un10** [comment]
Sounds good @eug48. Whatever you think will be easiest to get something functional while meeting the requirements.

I did an update to the definition to have a profile object. I suspect that may be all you need now. This could be read with a GET request and saved with a PUT request. Also, on the initial registration it will be created by a POST request. Does this make sense?

Have a look [here](https://editor.swagger.io/?url=https://raw.githubusercontent.com/HealthHackAu2020/Oscar/dev/swagger.yml) and feel free to edit if you have any other suggestions. It's committed in github [here](https://github.com/HealthHackAu2020/Oscar/blob/dev/swagger.yml)

I was also wondering, if there is any benefit to having an API for the content. That way, there could be a separate admin tab where Molly and/or others could change the catalog of activities, quotes etc. (or, alternatively, I could build a simple standalone react app for capturing this information).

**Comment by eug48** [comment]
Okay, cool. Yes `/profile` looks to be enough. Is it possible to have it take a schema-less object though? Or is there a more efficient editor for swagger schemas? ;)

Will yourself and/or @NickSolante be working on the authentication code that would need to go in the front-end?

I think a content API is potentially useful (app store updates may not get installed) but I would think lower priority. The activities may have rich-ish content like bullet points that would also complicate an editor.

**Comment by m0un10** [comment]
I was only planning on using swagger for communication and creating a shared understanding of what interfaces we need (and maybe for mocks during development). I didn’t have any intention to use it for validation so with the use of a NoSQL backend we will be able to accept any payload. If that was the concern? Or, was your concern more that the swagger definition was too hard to edit?

I’m happy to be utilised anywhere that I can help best. I don't have any concern with owning the authentication code if that is your preference.

I didn’t quite understand the comment - “app store updates may not get installed”. Can you please clarify?

Maybe the rich-content could be stored in markdown and rendered in HTML? What do you think?

I’ll work on breaking down the tasks related to auth and API today in preparation for the weekend.

**Comment by eug48** [comment]
Yep, I would just prefer the backend accept any payload (at least for now) to make development quicker, so that sounds good. I'm not particularly familiar with swagger so didn't want to spend much time editing that yaml.

After my comment I noticed that @NickSolante has already made some progress on auth which is great.

With “app store updates may not get installed” I mean that the advantage of a content API is that users can get updated content even if they don't bother to install a new version of the app from the app store.

Oh yeah, Markdown sounds reasonable. https://github.com/markdown-it/markdown-it claims to be safe from XSS and can be used in the frontend.

**Comment by m0un10** [comment]
Excellent. Here's a bit of a summary of what I think we'll need and where it's at. Might look daunting but most of the tasks are pretty simple just a few lines of code I think. I'm probably going to look at some of the things in advance of this weekend so we can hit the ground running.

| Task | Notes | Status | Assigned to |
| ---- | ------ | ----- | ------- |
| Create a login page | . | done | @NickSolante | 
| Connect the login with an auth service | using firebase auth | done | @NickSolante |
| Store the session in the context | . | done | @m0un10 |
| Create signup & login buttons for when the user is unauthorised | . | done | @m0un10 |
| Create a logout menu item | tested logout but need to find a better place for the logout button | in progress | @m0un10 |
| Load the state from the session | . | done | @m0un10 |
| Clear the session on logout | . | done | @m0un10 |
| Redirect on login and logout | . | done | @m0un10 |
| Create a signup page | . | done | @NickSolante | 
| Connect the sign up with a user store | using firebase auth | done | @NickSolante | 
| Setup a route that redirects unauthorised requests | . | done | @m0un10  |
| Switch the secure pages to use the secure route | components created but need to wire them up | in progress | @m0un10 |
| Redirect back to the original request after login | working through an issue | in progress | @m0un10  |

Stretch goals (to be included if time permits)

| Task | Notes | 
| ---- | ----- | 
| Content management API | . | 
| Social login | . | 
| Forgotten password | . | 
| Password change menu | . | 
| Email change menu | . | 
| Establish backend secret management (if applicable) | . | 
| Introduce react hooks for reusing any of the stateful logic | . | 
| Give feedback (e.g. spinning icon) when logging in is happening | . | . | . |
| Remember me checkbox so the user can choose to not be persisted | . | . | . |

**Comment by m0un10** [comment]
Put some details [here](https://github.com/HealthHackAu2020/Oscar/blob/dev/features/onboarding.feature) about how the register and login should working according with @lewismo 's description on Miro.
