### ISSUE TITLE
Remove or align on formatting

### ISSUE THREAD

**Issue by m0un10** [HealthHackAu2020/Oscar#14]
It becomes really hard to see what has actually changed from a functional perspective in the git history when there is inconsistent auto-formatting. This is because even opened files can show a huge amount of changes. A good example of this happening is [here](https://github.com/HealthHackAu2020/Oscar/commit/5a61de7a6b1ac6004a65c08d09e1308766337fe0).

@NickSolante would be good if auto-formatting in IDE is turned off, so it doesn't show so many changes in git when nothing has actually changed.... at least, that is what I am thinking.
Or maybe, we all align to what you have! 😄 
ha6

**Comment by NickSolante** [comment]
Im really sorry about that, Ill disable it now

**Comment by m0un10** [comment]
No problem man! I've also been know to make this blunder in the past ha2

**Comment by NickSolante** [comment]
I've turned it off now
