### ISSUE TITLE
Add Licence

### ISSUE THREAD

**Issue by eug48** [HealthHackAu2020/Oscar#15]
Proposal is:

For code: Apache 2.0
For graphics (created from scratch by @lewismo): https://creativecommons.org/licenses/by/4.0/
(Text currently used with permission from www.tameyourgut.com and Anxiety Canada)

Please comment whether you agree

**Comment by eug48** [comment]
I agree :)

**Comment by NickSolante** [comment]
Agree

**Comment by m0un10** [comment]
No concern from me!

**Comment by sachix1001** [comment]
I agree!

**Comment by lewismo** [comment]
Agree!
